### ISSUE TITLE
Does it implements Relationship methods?

### ISSUE THREAD

**Issue by AlexanderZon** [bendl/CSharp-Eloquent-ORM#1]
hasOne
hasMany
belongsTo
belongsToMany
morphTo 
morphToMany

**Comment by bendl** [comment]
It doesn't sorry.

Idea was to create something similar to Laravel's Eloquent ORM yet stored in memory but I didn't get very far.

Best bet is to look at (much) more complete ORMs like NHibernate or Entity Framework.

Thanks.
